//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    public enum Должность
    {
        
        // *** Start programmer edit section *** (Должность.Кладовщик CustomAttributes)

        // *** End programmer edit section *** (Должность.Кладовщик CustomAttributes)
        Кладовщик,
        
        // *** Start programmer edit section *** (Должность.Менеджер CustomAttributes)

        // *** End programmer edit section *** (Должность.Менеджер CustomAttributes)
        Менеджер,
    }
}
